CREATE TABLE order_details(
order_details_id INT,
order_id INT,
pizza_id VARCHAR(50),
quantity INT
);
CREATE TABLE orders(
order_id INT,
date_ DATE,
time_ TIME
);
CREATE TABLE pizza_types(
pizza_type_id VARCHAR(100),
name_ VARCHAR(100),
category VARCHAR(50),
ingredients VARCHAR(200)
);
CREATE TABLE pizzas(
pizza_id VARCHAR(50),
pizza_type_id VARCHAR(100),
size_ VARCHAR(5),
price FLOAT,
FOREIGN KEY (pizza_type_id) REFERENCES pizza_types(pizza_type_id)
);
-- Q1. Total orders.
SELECT COUNT(order_details_id) FROM order_details;
-- Q2. Total quantity sold.
SELECT COUNT(quantity) FROM order_details; 
-- Q3. Pizza price list.
SELECT pizza_types.name_ , pizzas.size_ , pizzas.price FROM pizza_types JOIN pizzas
ON pizza_types.pizza_type_id = pizzas.pizza_type_id;
-- Q4. Unique piza category.
SELECT DISTINCT category FROM pizza_types;
-- Q5. Most expensive pizza.
SELECT pizza_types.name_, pizzas.price  FROM pizzas JOIN pizza_types
ON pizzas.pizza_type_id = pizza_types.pizza_type_id
ORDER BY pizzas.price  DESC
LIMIT 1;
-- Q6. Orders per day.
SELECT EXTRACT(DAY FROM date_) AS Day_ , COUNT(order_id) AS no_of_orders FROM orders 
GROUP BY EXTRACT(DAY FROM date_)
ORDER BY EXTRACT(DAY FROM date_);

-- Q7. most ordered pizza.
SELECT pizza_id  FROM order_details
ORDER BY quantity DESC
LIMIT 1;
-- Q8. orders by pizza size.
SELECT COUNT(quantity)  FROM order_details
GROUP BY pizza_id;
-- Q9. Top 5 most ordered pizzas. //LOGICAL ERORR!!
SELECT pizza_id FROM order_details
ORDER BY quantity DESC
LIMIT 5;
-- Q10. Category wise pizza count.
SELECT category ,COUNT(pizza_type_id) FROM pizza_types
GROUP BY category;
-- Q11. Revenue generated by each pizza.
SELECT pizza_type_id, SUM(price) FROM pizzas
GROUP BY pizza_type_id;
-- Q12. Total revenue.
SELECT SUM(price) AS Total_revenue FROM pizzas;
-- Q13.revenue by category.
SELECT pizza_types.category, SUM(pizzas.price) AS Revenue  FROM pizzas JOIN pizza_types
ON pizza_types.pizza_type_id = pizzas.pizza_type_id
GROUP BY pizza_types.category;
-- Q14. Peak ordering hours.
SELECT EXTRACT(HOUR FROM time_) AS HOUR_, COUNT(order_id) FROM orders
GROUP BY EXTRACT(HOUR FROM time_)
ORDER BY EXTRACT(HOUR FROM time_);
-- Q15. Average price by pizza size.
SELECT pizza_id , AVG(price) AS avg_price FROM pizzas
GROUP BY pizza_id
ORDER BY pizza_id;
-- Q16. Find the category with the highest total quantity sold.
SELECT   pt.category, SUM(od.quantity) AS total_qty FROM order_details od
JOIN pizzas p  
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt 
ON p.pizza_type_id  = pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_qty DESC
LIMIT    1;
-- Q17. Find pizzas that were never ordered.
SELECT
    p.pizza_id,
    p.size_,
    p.price
FROM pizzas p
LEFT JOIN order_details od ON p.pizza_id = od.pizza_id
WHERE od.pizza_id IS NULL;

-- Q18. Find all orders where total quantity is greater than 3.
SELECT
    order_id,
    SUM(quantity) AS total_qty
FROM order_details
GROUP BY order_id
HAVING SUM(quantity) > 3;

-- Q19. Find which pizza size generates the highest revenue.
SELECT
    p.size_,
    SUM(p.price * od.quantity) AS revenue
FROM pizzas p
JOIN order_details od ON p.pizza_id = od.pizza_id
GROUP BY p.size_
ORDER BY revenue DESC
LIMIT 1;

-- Q20. Find orders where quantity is greater than average quantity.
SELECT
    order_details_id,
    order_id,
    pizza_id,
    quantity
FROM order_details
WHERE quantity > (
    SELECT AVG(quantity)
    FROM order_details
);

-- Q21. Find the second highest priced pizza.
SELECT DISTINCT
    pizza_id,
    pizza_type_id,
    size_,
    price
FROM pizzas
ORDER BY price DESC
LIMIT 1 OFFSET 1;

-- Q22. Find the category that generated the highest revenue.
SELECT
    pt.category,
    SUM(p.price * od.quantity) AS revenue
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY revenue DESC
LIMIT 1;

-- Q23. Find the most ordered pizza in each category.
SELECT
    category,
    pizza_id,
    total_qty
FROM (
    SELECT
        pt.category,
        od.pizza_id,
        SUM(od.quantity) AS total_qty,
        RANK() OVER (
            PARTITION BY pt.category
            ORDER BY SUM(od.quantity) DESC
        ) AS rnk
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category, od.pizza_id
) ranked
WHERE rnk = 1;

-- Q24. Find orders that contain more than one type of pizza.
SELECT
    od.order_id,
    COUNT(DISTINCT p.pizza_type_id) AS type_count
FROM order_details od
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY od.order_id
HAVING COUNT(DISTINCT p.pizza_type_id) > 1;
-- 25. Show cumulative revenue over time.
SELECT
    o.date_,
    SUM(p.price * od.quantity) AS daily_revenue,
    SUM(SUM(p.price * od.quantity)) OVER (ORDER BY o.date_) AS running_total
FROM orders o
JOIN order_details od ON o.order_id = od.order_id
JOIN pizzas p ON od.pizza_id = p.pizza_id
GROUP BY o.date_
ORDER BY o.date_;

-- 26. Use a Common Table Expression to calculate daily revenue and display it.
WITH daily_revenue AS (
    SELECT
        o.date_,
        SUM(p.price * od.quantity) AS revenue
    FROM orders o
    JOIN order_details od ON o.order_id = od.order_id
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY o.date_
)
SELECT
    date_,
    revenue
FROM daily_revenue
ORDER BY date_;

-- 27. Find the top 3 pizzas generating highest revenue using a CTE.
WITH pizza_revenue AS (
    SELECT
        od.pizza_id,
        SUM(p.price * od.quantity) AS revenue
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY od.pizza_id
)
SELECT
    pizza_id,
    revenue
FROM pizza_revenue
ORDER BY revenue DESC
LIMIT 3;

-- 28. Rank pizzas based on revenue from highest to lowest using CTE.
WITH pizza_revenue AS (
    SELECT
        od.pizza_id,
        SUM(p.price * od.quantity) AS revenue
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY od.pizza_id
)
SELECT
    pizza_id,
    revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM pizza_revenue
ORDER BY revenue_rank;

-- 29. Calculate average revenue per order using a CTE.
WITH order_revenue AS (
    SELECT
        od.order_id,
        SUM(p.price * od.quantity) AS order_total
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    GROUP BY od.order_id
)
SELECT
    ROUND(AVG(order_total)::NUMERIC, 2) AS avg_order_value
FROM order_revenue;
-- 30. Find percentage contribution of each category in total revenue using CTE.
WITH cat_revenue AS (
    SELECT
        pt.category,
        SUM(p.price * od.quantity) AS revenue
    FROM order_details od
    JOIN pizzas p ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category
),
total_revenue AS (
    SELECT
        SUM(revenue) AS grand_total
    FROM cat_revenue
)
SELECT
    c.category,
    ROUND(c.revenue::NUMERIC, 2) AS revenue,
    ROUND((c.revenue * 100.0 / t.grand_total)::NUMERIC, 2) AS contribution_pct
FROM cat_revenue c
CROSS JOIN total_revenue t
ORDER BY contribution_pct DESC;